# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/IaC-ARMDeployTest'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'IaC_ARM_Template_Dev'
    subscriptionId: 'fb7c94b5-7744-429b-a7ae-db1458359f71'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'IaC-ARMDeployTest-RG'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory).\IaC-ARMDeployTest\identitydeploy.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory).\IaC-ARMDeployTest\identitydeploy.parameters.json'
    deploymentMode: 'Incremental'
- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory).\IaC-ARMDeployTest\keyvault.ps1'